<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'));
	$url_edit = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-6 control-label">
															<?php echo $tr->translate("WHEREHOUSE_ID")?>
														</label>
													<div class="col-sm-6">
															<?php echo $form->getElement('wherehouse_id');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<div class="col-sm-12">
															<?php echo $form->getElement('handow');?>
														</div>
												</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-6 control-label">
															<?php echo $tr->translate("DOCUMENT#")?>
													</label>
													<div class="col-sm-6">
															<?php echo $form->getElement('3');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<label class="col-sm-6 control-label">
															<?php echo $tr->translate("SESSION#")?>
													</label>
													<div class="col-sm-6">
															<?php echo $form->getElement('7');?>
														</div>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-12">
											<div class="col-sm-12">
												<div class="tabbable" id="tabShow">
													<ul id="myTab" class="nav nav-tabs">
														<li class="active"><a href="#myTab_example1"
															data-toggle="tab"> <i class="green fa fa-gear"></i> <?php echo $tr->translate("General Information")?>
																</a></li>
														<li><a href="#myTab_example2" data-toggle="tab"> <i
																class="green fa fa-gear"></i> <?php echo $tr->translate("Item_Details")?>
																</a></li>
														
														
													</ul>
													<div class="tab-content">
														<div class="tab-pane fade in active" id="myTab_example1">
														</div>
														<div class="tab-pane fade" id="myTab_example2">
															<div class="form-group">
																<div class="form-group">
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("ITME_CODE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('item_code');?>
																		</div>
																		
																		<div class="col-sm-6">
																				<?php echo $form->getElement('ptd_usage_value');?>
																		</div>
																	 </div>
													    		</div>
													    		<div class="form-group">
																	 <div class="form-group col-sm-12">
																	 	<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("BRANCH")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('branch');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("QTY")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		
																	 </div>
																	 <div class="form-group">
																		 <div class="form-group col-sm-12">
																			<label class="col-sm-2 control-label" for="form-field-1">
																					<?php echo $tr->translate("BLANK_SMALER")?>
																			</label>
																			<div class="col-sm-4">
																					<?php echo $form->getElement('blank_smaler');?>
																			</div>
																			
																			<div class="col-sm-6">
																					<?php echo $form->getElement('ptd_usage_value');?>
																			</div>
																		 </div>
														    		</div>
														    		<div class="form-group col-sm-12">
																		<div class="col-sm-2">
																				<input type="radio" class="grey" name="optionsRadios" value="unit_cost"/>
																		</div>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		<div class="col-sm-2">
																				 <input type="radio" class="grey" name="optionsRadios" value="Total_cost"/>
																		</div>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		
																	 </div>
																	  <div class="form-group col-sm-12">
																	 	<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("SERIAL")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('serial');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LOT")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('lot');?>
																		</div>
																		
																	 </div>
																	 <div class="form-group col-sm-12">
																		<div class="col-sm-3">
																				<?php echo $form->getElement('add_lind');?>
																		</div>
																		<div class="col-sm-3">
																				<?php echo $form->getElement('edit_lind');?>
																		</div>
																		<div class="col-sm-3">
																				<?php echo $form->getElement('delete_lind');?>
																		</div>
																		<div class="col-sm-3">
																				<?php echo $form->getElement('concel_lind');?>
																		</div>
																		
																	 </div>
													    		</div>
															</div>
														</div>
													</div>
											<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>ITEM_CODE</th>
																<th class="hidden-xs">DISCRIPTION</th>
																<th>QTY</th>
																<th>UNIT_ID</th>
																<th>UNIT_COST</th>
																<th>TOTAL_COST</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td> 001</td>
																<td>tiger can</td>
																<td></td>
																<td>1.000</td>
																<td> 199.000</td>
																<td>CAN</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>