<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'));
	$url_edit = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-4 control-label">
															<?php echo $tr->translate("ITEM_CODE")?>
														</label>
													<div class="col-sm-8">
															<?php echo $form->getElement('item_code');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<div class="col-sm-12">
															<?php echo $form->getElement('qty_handow');?>
														</div>
												</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-4 control-label">
															<?php echo $tr->translate("WHEREHOUSE_ID")?>
														</label>
													<div class="col-sm-8">
															<?php echo $form->getElement('wherehouse_id');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<div class="col-sm-12">
															<?php echo $form->getElement('handow');?>
														</div>
												</div>
											</div>
						
										</div>
											<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-12">
											<div class="col-sm-12">
												<div class="tabbable" id="tabShow">
													<ul id="myTab" class="nav nav-tabs">
														<li class="active"><a href="#myTab_example1"
															data-toggle="tab"> <i class="green fa fa-gear"></i> <?php echo $tr->translate("General Information")?>
																</a></li>
														<li><a href="#myTab_example2" data-toggle="tab"> <i
																class="green fa fa-gear"></i> <?php echo $tr->translate("Cost-usage")?>
																</a></li>
														<li><a href="#myTab_example3" data-toggle="tab"> <i
																class="green fa fa-gear"></i> <?php echo $tr->translate("note")?>
																</a></li>
														
													</ul>
													<div class="tab-content">
														<div class="tab-pane fade in active" id="myTab_example1">
														<div class="form-group">
															<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("SUPER_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('product_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background');?>
																	</div>
																  </div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("PART_NUMBER")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('stock_unit_id');?>
																	</div>
																	
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("STOCK_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('puchase_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background2');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("PURCHASE_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('sale_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("SALE_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('part_number');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("LEAD_TIME")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_POIN")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_QTY")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_QTY2")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																</div>
																 
													    	</div>
														</div>
														</div>
														<div class="tab-pane fade" id="myTab_example2">
															<div class="form-group">
																<div class="form-group">
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("STANDART_COST")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_Usage_value")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_usage_value');?>
																		</div>
																	 </div>
													    		</div>
													    		<div class="form-group">
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("QTY_ONHAND")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_Usage_qty")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_usage_qty');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("AVERAGE_COST")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('average_cost');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_sale_value")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_sale_value');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_RECEIVE_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_receive_date');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_sale_qty")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_sale_qty');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_SALE_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_sale_date');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_COUNT_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_count_date');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_ORDER_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_order_date');?>
																		</div>
																	 </div>
													    		</div>
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example3">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example4">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example5">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example6">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example7">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example8">
															<div class="form-group">
															</div>
														</div>
													</div>
													<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>ITEM_CODE</th>
																<th>BRANCH</th>
																<th class="hidden-xs">DISCRIPTION</th>
																<th>SECOND_LANGAUGE</th>
																<th>AVG.COST</th>
																<th>HANDON</th>
																<th>STOCK_UNIT</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>001</td>
																<td> 001</td>
																<td>tiger can</td>
																<td></td>
																<td>1.000</td>
																<td> 199.000</td>
																<td>CAN</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
												</div>
											</div>
										</div>
									</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>