<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'customer','controller'=>'customer','action'=>'add'));
	$url_edit = $this->url(array('module'=>'customer','controller'=>'customer','action'=>'index'),null,true);
?>
<title><?php echo $tr->translate("CUSTOMER"); ?></title>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("CUSTOMER")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" action="<?php echo $url_save; ?>">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_ID ")?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_id');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("APPLY_TOCOMPANY ")?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('apply');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY  ")?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('company');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("CURRENT_BALANCE  ")?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('current');?>
								</div>
							</div>
						</div>
						<div class="form-group">
						  <div class="col-md-6">
						   <div class="form-group">
						       <label class="control-label col-md-4"><?php echo $tr->translate("SECOND_LANGUAGE   ")?> <span class="required">
								</span>
								</label>
								<div class="col-md-8">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('second_language');?>
									</div>
								</div>
						   </div>
						   <div class="form-group">
						       <label class="control-label col-md-4"><?php echo $tr->translate("CONTACT_NAME   ")?> <span class="required">
								</span>
								</label>
								<div class="col-md-8">
									<div class="input-icon right">
										<i class="fa"></i>
										<?php echo $form->getElement('contact');?>
									</div>
								</div>
						   </div>
						   <div class="form-group">
						        <label class="control-label col-md-4"><?php echo $tr->translate("YTD_SALE   ")?> <span class="required">
								</span>
									</label>
									<div class="col-md-8">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('sale');?>
										</div>
									</div>
						   </div>
						   <div class="form-group">
						        <label class="control-label col-md-4"><?php echo $tr->translate("MOBILE_PHONE   ")?> <span class="required">
								</span>
									</label>
									<div class="col-md-8">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('mobile');?>
										</div>
									</div>
						   </div>
							<div class="form-group">
							<label class="control-label col-md-4"><?php echo $tr->translate(" AVILABLE_CREDIT   ")?>  <span class="required">
								 </span>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_group');?>
								</div>
							</div>
							</div>
							
						 </div>
						 <div class="col-md-6">
						   <div class="form-group">
							<label class="control-label col-md-4"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
							<div class="col-md-8">
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											</div>
											<div>
												<span class="btn default btn-file">
												<span class="fileinput-new">
												Select image </span>
												<span class="fileinput-exists">
												Change </span>
												<input type="file" name="...">
												</span>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
									</div>
								</div>
							</div>
						  </div>
						 </div>
						</div>
					    <div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate(" CUSTOMER_GROUP_ID  ")?>  <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_group');?>
								</div>
							</div>
							<div class="form-group">
                                  <div class=" col-md-6">
									<label class="col-md-2"><?php echo $tr->translate("ACTIVE")?></label>
									<div class="col-md-3"><?php echo $form->getElement('active');?></div>
									<label class="col-md-2"><?php echo $tr->translate("ON_HOLD")?></label>
									<div class="col-md-3"><?php echo $form->getElement('hold');?></div>
						         </div>
						    </div>
						</div>
							<div class="col-sm-12" style="padding: 0;background: #fff;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable"  id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background: #5F8295 none repeat scroll 0% 0%;">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("SALE_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("CUSTOMER_DETAIL")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example4" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("MEMBERSHIP")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example5" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
															
														</ul>
														<div class="tab-content">
															<div class="tab-pane fade in active" id="myTab_example1">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PHONE_2")?> 
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('phone_2');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TITLE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('title');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS_2")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address_2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CITY")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('city');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("COUNTRY")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('country');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX_2")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web_page');?>
																	</div>
																</div>																											
														</div>
															<div class="tab-pane fade" id="myTab_example2">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CREDIT_LIMIT")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('credit_limit');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("SALE_PERSON")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('sale_person');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PRICE_CODE")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('price_code');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TERM_ID")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('term_id');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PAYMENT_DAY")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('payment_day');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PAYMENT_DISC")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('payment_disc');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("NET_DUE")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('net_due');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("SALE_TAX")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('sale_tax');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("SALE_DISCOUNT")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('sale_discount');?>
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example3">
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("ENTRY_DATE")?>
																	</label>
																	<div class="col-sm-4">
																		<div class="input-group  date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
																			<?php echo $form->getElement('entry_date');?>
																			<span class="input-group-btn">
																			<button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
																			</span>
																		</div>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("DEPOSIT")?>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('deposit');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("LAST_SALE_DATE")?>
																	</label>
																	<div class="col-sm-4">
																		<div class="input-group  date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
																			<?php echo $form->getElement('last_sale_date');?>
																			<span class="input-group-btn">
																			<button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
																			</span>
																		</div>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("LAST_PAY_DATE")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('last_pay_date');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("PTD_SALES")?>
																	</label>
																	<div class="col-sm-4">
																		<div class="input-group  date-picker input-daterange" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
																			<input class="form-control" name="from" type="text">
																			<span class="input-group-addon">
																			to </span>
																			<?php echo $form->getElement('ptd_sales');?>
																		</div>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CREDIT")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('credit');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("LAST_SALE_AMOUNT")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('last_sale_amount');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("LAST_PAY_AMOUNT")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('last_pay_amount');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("CURRENT_BALANCE")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('current_balance');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("YTD_SALES")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('ytd_sales');?>
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example4">
															    <div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("MEMBERSHIP_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('membership_id');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("MEMBERSHIP_TYPE")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('membership_type');?>
																	</div>
																</div>
															    <div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("MEMBER_DAYS")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('member_days');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("SEX")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('sex');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("DATE_OF_BIRTH")?>
																	</label>
																	<div class="col-sm-4">
																			<div class="input-group  date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
																				<?php echo $form->getElement('date_of_birth');?>
																				<span class="input-group-btn">
																				<button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
																				</span>
																			</div>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ENROLL_DATE")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('enroll_date');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("LAST_BILL_DATE")?>
																	</label>
																	<div class="col-sm-4">
																			<div class="input-group  date date-picker" data-date-format="dd-mm-yyyy" data-date-start-date="+0d">
																				<?php echo $form->getElement('last_bill_date');?>
																				<span class="input-group-btn">
																				<button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
																				</span>
																			</div>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("NEXT_BILL_DATE")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('next_bill_date');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("VALID_TO")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('valid_to');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TOTAL_USEd_TIME")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('total_used_time');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("LAST_USED_DATE")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('last_used_date');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TOTAL_AMOUNT")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('total_amount');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("LAST_AMOUNT")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('last_amount');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CURRENT_POINT")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('current_point');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" >
																		<?php echo $tr->translate("TOTAL_POINT")?>
																	</label>
																	<div class="col-sm-4">
																				<?php echo $form->getElement('total_point');?>
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example5">
															    <div class="form-group">
																	<div class="col-sm-12">
																			<?php echo $form->getElement('note');?>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
					</div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/customer/customer/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>