<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'setting','controller'=>'costchange','action'=>'add'));
	$url_edit = $this->url(array('module'=>'setting','controller'=>'costchange','action'=>'index'),null,true);
?>
<div class="row"> 
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption" style="margin-bottom:5px;">
					<i class="icon-home"></i><?php echo $tr->translate("COMPANY SETTING")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
				
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("RECEIVE_DATE_FORM")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('receive');?>
												</div>
											</div><div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("TO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('to');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_CODE_FORM")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('item');?>
												</div>
											</div><div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("TO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('to1');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LOCATION_ID_FORM")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('location');?>
												</div>
											</div><div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("TO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('to2');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SUPPLIER_ID_FORM")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('supply');?>
												</div>
											</div><div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("TO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('to3');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("PROJECT_ID_FORM")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('supply');?>
												</div>
											</div><div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("TO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('to4');?>
												</div>
											</div>
										</div>
						
				</form>
			</div></div>
		</div>
	</div>
