<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'group','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'edit'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="fa fa-globe"></i>MENU_GROUP</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-bordered table-hover" id="sample_2">
							<thead>
							<tr>
								<th>
							    	id
								</th>
								<th>
									menu_code
								</th>
								<th>
									desc
								</th>
								<th>
									 lang_one
								</th>
								<th>
									 lang_two
								</th>
								<th>
									show_description
								</th>
								<th>
									 apply_company
								</th>
								<th>
									status
								</th>
								
								
							</tr>
							</thead>
							<tbody>
							<tr>
							<?php foreach ($this->rows as $key =>$row){?>
							       <tr class="odd" role="row">
							        <td><?php echo $key+1;?></td>
							        <td><?php echo $row["menu_code"];?></td>
							        <td><?php echo $row["desc"];?></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang1"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang2"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["display_by"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["apply_company"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["status"];?></a></td>
							       </tr>
							    <?php }?>
							</tr>
							</tbody>
					</table>
					<div class="tools">
						<a href="<?php echo $url;?>"><button type="button" name="btnsave" class="btn btn-primary">
						<i class="icon-plus"></i> <?php echo $tr->translate("ADD_NEW")?> </button></a>
						<a href="<?php echo $this->baseUrl();?>/menu">
						<button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
					</div>
				</div>
				<div class="row">
					
				</div>
				
		</div>
	</div>