<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
									<div class="col-sm-5" style="padding: 5px;">
										<div class="form-group">
											<label class="col-sm-4 control-label">
												<?php echo $tr->translate("MENU_GROUP")?> <span class="symbol required"></span>
											</label>
											<div class="col-sm-8">
												<?php echo $form->getElement('menu_code');?>
											</div>
										</div>
										<div class="panel-body table-responsive" id="panel-body">
											<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("DESCRIPTION")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("MENU_ITEM")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_ONE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_TWO")?></th>
															</tr>
														</thead>
													<tbody>
															<tr style="font-size: 11px;">
																<td>Amaya</td>
																<td class="hidden-xs">W3C,
																INRIA</td>
																<td>Free</td>
																<td class="hidden-xs">W3C</td>
															</tr>
															<tr style="font-size: 11px;">
																<td>AOL Explorer</td>
																<td class="hidden-xs">America Online, Inc</td>
																<td>Free</td>
																<td class="hidden-xs">Proprietary</td>
															</tr>
													</tbody>
												</table>
											</div>
										</div>
										<div class="col-sm-7" style="padding: 5px;border-left: 1px solid #698A9C;">
											<div class="form-group">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LOCATION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('menu_code');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('menu_code');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("ITEM_CODE")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('menu_code');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("QUANTITY")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="form-group">	
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("COMBO_ITEM")?>
												</label>											
												<div class="col-sm-1">
													<label class="checkbox-inline">
													<?php echo $form->getElement('combo');?>
													</label>													
												</div>
												
											</div>
											<div class="panel-body table-responsive" id="panel-body">
												<table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("DESCRIPTION")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("ITEM_CODE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LOCATION")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("QTY")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("UNIT")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("COST")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("TOTAL")?></th>
															</tr>
														</thead>
													<tbody>
															<tr style="font-size: 11px;">
																<td style="text-align: center;">1</td>
																<td>Amaya</td>
																<td style="text-align: center;">1</td>
																<td class="hidden-xs">W3C,
																INRIA</td>
																<td>Free</td>
																<td class="hidden-xs">W3C</td>
																<td style="text-align: center;">1</td>
															</tr>
															<tr style="font-size: 11px;">
																<td style="text-align: center;">2</td>
																<td style="text-align: center;">1</td>
																<td style="text-align: center;">1</td>
																<td>AOL Explorer</td>
																<td class="hidden-xs">America Online, Inc</td>
																<td>Free</td>
																<td class="hidden-xs">Proprietary</td>
															</tr>
													</tbody>
												</table>
											</div>
										</div>
									</div>
					</div>
					
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					
				</form>
			</div>
		</div>
	</div>
</div>