<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'combo','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'combo','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
							<div class="col-sm-9">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("COMBO_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('combo_code');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("SHOW_DESCRIPTION")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("PRICE")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('price');?>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="control-label col-md-4"><?php echo $tr->translate("IMAGE")?> <span class="required">
													 </span>
												</label>
												<div class="col-md-8">
													<div class="form-group last">
														<div class="col-md-12">
															<div class="fileinput fileinput-new" data-provides="fileinput" style="width: 200px; height: 150px;">
																<label id="display_titel" class="full-size" style="border:1px solid #ccc;">
																	<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" style="padding:3px ;background:#7C9BAB none repeat scroll 3px;"/>
																</label>
																<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
																</div>
																<div>
																	<?php echo $form->getElement('photo');?>
																	<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
																	Remove </a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
													<div class="tabbable" id="tabShwo" style="">
														<ul id="myTab" class="nav nav-tabs" style="background-color:#65879A;">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("FORMAT")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
														<div class="tab-content">
															<div class="tab-pane fade in active" id="myTab_example1">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("MENU_GROUP_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('menu_group');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("ROOT_MENU_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('root_menu');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("PRINTER_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('printer_code');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="col-sm-2" style="font-size: 10px;">
																		<?php echo $form->getElement('combo');?>
																		<?php echo $tr->translate("ROOT_MENU")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo1');?>
																		<?php echo $tr->translate("PRINT_TO_PRINTER")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo2');?>
																		<?php echo $tr->translate("SHOW_SCREEN")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo3');?>
																		<?php echo $tr->translate("DISCOUNT")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo4');?>
																		<?php echo $tr->translate("REQUIR_CHOOE_MENU")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<label class="col-sm-9" style="margin: 0; padding: 0;"><?php echo $tr->translate("REQUIRE_NUM")?></label>
																		<div class="col-sm-3"  style="margin: 0; padding: 0;"><?php echo $form->getElement('demo4');?></div>																												
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6">
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("APPLY_TO_COMPANY")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('apply_to_company');?>
																		</div>
																	</div>
																</div>											
															</div>
														</div>
														<div class="tab-pane fade in " id="myTab_example2">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("BACK_COLOR")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('backgroun_color');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("FONT_COLOR")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('font_color');?>
																		</div>
																	</div>
																	
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_SIZE")?>
																	</label>
																	<div class="col-sm-3">
																		<div id="spinner4">
																			<div class="input-group" >
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-up blue">
																					<i class="fa fa-plus"></i>
																					</button>
																				</div>
																				<?php echo $form->getElement('font_size');?>
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-down red">
																					<i class="fa fa-minus"></i>
																					</button>
																				</div>
																			</div>
																		</div>  
																	</div>
																</div>
															</div>		
														</div>
														<div class="tab-pane fade in " id="myTab_example3">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-12" >
																		<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("NOTE")?>
																		</label>
																		<div class="col-sm-11">
																			<?php echo $form->getElement('note');?>
																		</div>
																	</div>
																</div>
															</div>		
														</div>
													</div>															
												</div>
											</div>
										</div>
										</div>
					</div>
					
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="btnsaveclose"class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu/combo/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					
				</form>
			</div>
		</div>
	</div>
</div>
 <form  class="form-horizontal" enctype="multipart/form-data" method="post" id="popup" style="display:none;position: absolute;" >
	<div class=" col-sm-6" style="background: #F2E2E2;">
        <div class="form-group col-sm-12">
		    <label class="col-sm-4 control-label" >
				<?php echo $tr->translate("MENU_GROUP_CODE ")?> <span class="symbol required"></span>
			</label>
			<div class="col-sm-8">
				<input class="form-control input-large"  type="text" name="new_menu_group" id="new_menu_group" required>
			</div>
		</div>
		<div class="form-group col-sm-12">
		    <label class="col-sm-4 control-label" >
				<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
			</label>
			<div class="col-sm-8">
				<input class="form-control input-large"  type="text" name="new_type_description" id="new_type_description" required >
			</div>
		</div>
		<div class="col-md-offset-3 col-md-9">
		    <button id="btn_add_type" type="button" name="btn_add_type" class="btn btn-primary" onClick="addNewType();"><i class="fa fa-save" ></i> SAVE_NEW </button>
			<button id="b_close_type" type="button" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> CLOSE </button>
		</div>
  </div>
 </form>
<script>
function poupUpForm(){
	popup=$('#menu_group').val();
	if(popup == -1){
		$('#popup').show(500);
		$('#popup').animate({top:"400px"},"fast");
	}
	else {
		$("#popup").hide(400);
    }
	$("#b_close_type").click(function() {
        $("#popup").hide(400);
        $('#menu_group').val("");
        $("#popup input[type=text]").val('');
        //location.reload();
    }); 
}
function displayPhoto(){
	dis_type=$("#show_description").val();
	bg_color= $("#backgroun_color").val();
	font_color= $("#font_color").val();
	font_size = $("#font_size").val();
	if(dis_type==1){
		dis_title = $("#combo_code").val();
	}else if(dis_type==2){
		dis_title = $("#description").val();
	}
	else if(dis_type==3){
		dis_title = $("#lang_1").val();
	}
	else if(dis_type==4){
		dis_title = $("#lang_2").val();
	}
	else{
		dis_title = '';
	}
	$("#display_titel").html(dis_title);
	$("#display_titel").css({"background-color": bg_color,"color": font_color,"font-size":font_size+"px" });
}

var url_type = "<?php echo $this->url(array('module'=>'menu','controller'=>'combo','action'=>'add-new-type'));?>";
function addNewType(){
	var new_menu_group = $('#new_menu_group').val();
	var new_type_description = $('#new_type_description').val();
	code_des=new_menu_group+"-"+new_type_description;
	if(new_type_description=="" || new_type_description == null){
		alert('Please input field!');
		$('input').focus();
	}else{
	 $.ajax({
         type: "POST",
         url: url_type,
         data: {'new_type_code':new_menu_group,'description':new_type_description}, // serializes the form's elements.
         success: function(data)
         {   $("#popup").hide(400);$("#popup input[type=text]").val('');//hide form and clear textField 
             value = $.parseJSON(data);
             //alert(value['id']);
             $('#menu_group').append($('<option></option>').attr('value',value['id']).attr("selected","selected").text(code_des)); 
             $("#menu_group").val(value['id']).trigger('change');
             $('#menu_group').trigger("liszt:updated");
             //alert("Insert Success"); // show response from the php script.
         },
		 error: function(e){
			 alert(e);
		 }
       });
	}

}
</script>