<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'combo','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'combo','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
							<div class="col-sm-9">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("COMBO_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('combo_code');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("SHOW_DESCRIPTION")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("PRICE")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('price');?>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="control-label col-md-4"><?php echo $tr->translate("IMAGE")?> <span class="required">
													 </span>
												</label>
												<div class="col-md-8">
													<div class="form-group last">
														<div class="col-md-12">
															<div class="fileinput fileinput-new" data-provides="fileinput">
																<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
																	<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
																</div>
																<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
																</div>
																<div>
																	<span class="btn default btn-file">
																	<span class="fileinput-new">
																	Select image </span>
																	<span class="fileinput-exists">
																	Change </span>
																	<input type="file" name="...">
																	</span>
																	<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
																	Remove </a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
													<div class="tabbable" id="tabShwo" style="">
														<ul id="myTab" class="nav nav-tabs" style="background-color:#65879A;">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("LOCATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
														<div class="tab-content">
															<div class="tab-pane fade in active" id="myTab_example1">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("MENU_GROUP_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('menu_group');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("ROOT_MENU_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('root_menu');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("PRINTER_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('printer_code');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="col-sm-2" style="font-size: 10px;">
																		<?php echo $form->getElement('combo');?>
																		<?php echo $tr->translate("ROOT_MENU")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo1');?>
																		<?php echo $tr->translate("PRINT_TO_PRINTER")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo2');?>
																		<?php echo $tr->translate("SHOW_SCREEN")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo3');?>
																		<?php echo $tr->translate("DISCOUNT")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<?php echo $form->getElement('combo4');?>
																		<?php echo $tr->translate("REQUIR_CHOOE_MENU")?>												
																	</div>
																	<div class="col-sm-2"  style="font-size: 10px;">
																		<label class="col-sm-9" style="margin: 0; padding: 0;"><?php echo $tr->translate("REQUIRE_NUM")?></label>
																		<div class="col-sm-3"  style="margin: 0; padding: 0;"><?php echo $form->getElement('demo4');?></div>																												
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6">
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("APPLY_TO_COMPANY")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('apply_to_company');?>
																		</div>
																	</div>
																</div>											
															</div>
														</div>
														<div class="tab-pane fade in active" id="myTab_example2">
															<div class="form-group">
															</div>		
														</div>
														<div class="tab-pane fade in active" id="myTab_example3">
															<div class="form-group">
															</div>		
														</div>
													</div>															
												</div>
											</div>
										</div>
										</div>
					</div>
					
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					
				</form>
			</div>
		</div>
	</div>
</div>