<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'setting','controller'=>'setting','action'=>'add'));
	$url_edit = $this->url(array('module'=>'setting','controller'=>'setting','action'=>'index'),null,true);
?>
<div class="row"> 
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption" style="margin-bottom:5px;">
					<i class="icon-home"></i><?php echo $tr->translate("BACK UP DATA")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_id');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_NAME")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_name');?>
												</div>
											</div>
											
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_NAME2")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_name2');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("GENDER")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('gender');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("LANGUAGE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('language');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("USER_LEVEL")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('user_level');?>
												</div>
											</div>
												
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("REPORT_LANGUAGE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('report_language');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("ACCESS_TO_COMPANY")?> <span class="symbol required"></span>
												</label>
											
												<div class="col-sm-8">
													<?php echo $form->getElement('access_to_company');?> 
												</div>
											</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("DEFAULT_COMPANY")?> <span class="symbol required"></span>
												</label>
											
												<div class="col-sm-8">
													<?php echo $form->getElement('default_company');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("PASSWORD")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('password');?>
												</div>
											</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("CONFIRM_PASSWORD")?> <span class="symbol required"></span>
												</label>
											
												<div class="col-sm-8">
													<?php echo $form->getElement('confirm_password');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("NOTE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('note');?>
												</div>
											</div>
											</div>
											
											
										   
							<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											</div>
											<div>
												<span class="btn default btn-file">
												<span class="fileinput-new">
												Select image </span>
												<span class="fileinput-exists">
												Change </span>
												<input type="file" name="...">
												</span>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
										<div class="clearfix margin-top-10">
											
										</div>
									</div>
								</div>
							</div>
						</div>
						
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>