<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_edit = $this->url(array('module'=>'customer','controller'=>'currency','action'=>'edit'));
?>
<title><?php echo $tr->translate("currency")?></title>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("currency")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" action="<?php echo $url_edit;?>">
				<div class="form-body">
				     <div  class="col-sm-12"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("CURRENCY_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-4">
												    <?php echo $form->getElement('id');?>
													<?php echo $form->getElement('currency_code');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("CURRENCY_TEXT ")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-2">
													<?php echo $form->getElement('currency_text');?>
												</div>
												<label class="col-sm-2 control-label">
													<?php echo $tr->translate("CURRENCY_SYMBLE ")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-2">
													<?php echo $form->getElement('currency_sy');?>
												</div>
												<label class="col-sm-2 control-label">
													<?php echo $tr->translate("DECIMAL_PLACE ")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-2">
													<?php echo $form->getElement('decimal');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label">
													<?php echo $tr->translate("EXCHANGE_RATE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('exchange');?>
												</div>
				                                  <div class=" col-md-6">
													<div class="form-group">
													<div class="radio-list">
														<label class="radio-inline">
														<input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" ><?php echo $tr->translate('CURRENCY_BASE');?> </label>
														<label class="radio-inline">
														<input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"><?php echo $tr->translate('BASE_CURRENCY');?> </label>
													</div>
												</div>
										         </div>
										</div>
				     </div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/customer/currency/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
