<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	    $url = $this->url(array('module'=>'customer','controller'=>'currency','action'=>'add'));
	    $url_edit = $this->url(array('module'=>'customer','controller'=>'currency','action'=>'edit'));
	    $rs= $this->rs;
	   // print_r($rs);exit();
?>
	<title><?php echo $tr->translate("CURRENCY");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("CURRENCY")?>
				</div>
				<div class="tools">
					<a href="<?php echo $url ;?>"><button type="button" name="btnsave" class="btn btn-primary"><i class="icon-plus"></i> <?php echo $tr->translate("ADD_NEW")?> </button></a>
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-bordered table-hover" id="sample_6">
							<thead>
							<tr>
							    <th>
									NO
								</th>
								<th>
									CURRENCY_CODE
								</th>
								<th>
									TEXT
								</th>
								<th class="hidden-xs">
									 SYMBLE
								</th>
								<th class="hidden-xs">
									DECIMAL_PLACE
								</th>
								<th class="hidden-xs">
									EXCHANG_RATE
								</th>
							</tr>
							</thead>
							<tbody>
							<?php foreach ($rs as $row){?>
							<tr class="odd" role="row">
							    <td> <?php echo $row["id"];?></td>
								<td> <a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["curr_code"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["curr_title"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["symbol"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["decimal_place"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["exchange_rate"];?></a></td>
							</tr>
					  	    <?php }?>
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
	</div>
