<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'table','controller'=>'tablegroup','action'=>'add'));
	$url_save_close = $this->url(array('module'=>'table','controller'=>'tablegroup','action'=>'add'));
?>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>

<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TABLES_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo $url_save; ?>" >
				<div class="form-body">
				     <div  class="col-sm-9"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("TABLE_GROUP_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<div class="input-icon right">
															<i class="fa"></i>
														<?php echo $form->getElement('group_code');?>
													</div>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
				     </div>
					 <div style="" class="col-sm-3" >
					             <div >
											<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<label id="display_titel" class="full-size">
													<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" style="padding:3px ;background:#7C9BAB none repeat scroll 3px;"/>
												</label>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											
											</div>
											<div>
												<?php echo $form->getElement('photo');?>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
									</div>
								</div>
						 </div>   
					 </div>		
					 		<div class="col-sm-12" style=";margin-top: 100px;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable" style="margin-top: -100px; " id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background:#7C9BAB 0px; ">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																	
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("FORMAT")?>
																</a>
															</li>
														</ul>
								<div class="tab-content">
									<div class="tab-pane fade in active" id="myTab_example1" class="col-sm-12">
                                     	<div class="form-group">
							                <label class="control-label col-md-2" value=""><?php echo $tr->translate("SHOW_DESCRIPTION")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="col-md-1">
												<div class="input-icon right">
													<i class="fa"></i>
												<span><?php echo $form->getElement('active');?></span>
												</div>
											</div>
											<label class="control-label col-md-1"><?php echo $tr->translate("ACTIVE")?> <span class="required">
												</span>
											</label>
                                  	</div>
                                  	
                                  	<div class="form-group">
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("APPLY_TO_COMPANY")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('apply_to_company');?>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
                                  	  <label class="control-label col-md-2"><?php echo $tr->translate("NOTE")?> <span class="required">
												</span>
											</label>
											<div class="form-group">																	
												<div class="col-sm-12">
												 <?php echo $form->getElement('note');?>
												</div>
										   </div>
                                  	</div>
			</div>
					<div class="tab-pane fade" id="myTab_example2">
											                   <div class="form-group">
													                 <label class="col-sm-2 control-label" for="form-field-1">
																       <?php echo $tr->translate("BACK_COLOR")?>
														       	    </label>
																   <div class="col-md-4">
																		<?php echo $form->getElement('backgroun_color');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_COLOR")?>
																	</label>
																	<div class="col-md-4">
																		<?php echo $form->getElement('font_color');?> 
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_SIZE")?>
																	</label>
																	<div class="col-sm-4">
																		<div id="spinner4">
																			<div class="input-group" >
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-up blue">
																					<i class="fa fa-plus"></i>
																					</button>
																				</div>
																				<?php echo $form->getElement('font_size');?>
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-down red">
																					<i class="fa fa-minus"></i>
																					</button>
																				</div>
																			</div>
																		</div>  
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
										</div>
							</div>			
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/table/tablegroup/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
function displayPhoto(){
	dis_type = $("#show_description").val();
	bg_color= $("#backgroun_color").val();
	font_color= $("#font_color").val();
	font_size = $("#font_size").val();
	group_code=$("#group_code").val();
	description=$("#description").val();
	lang_1=$("#lang_1").val();
	lang_2=$("#lang_2").val();
	if(dis_type==1){
		dis_title = $("#group_code").val();
		$("#display_titel").html(group_code);
	}else if(dis_type==2){
		dis_title = $("#description").val();
		$("#display_titel").html(description);
	}
	else if(dis_type==3){
		dis_title = $("#lang_1").val();
		$("#display_titel").html(lang_1);
	}
	else if(dis_type==4){
		dis_title = $("#lang_2").val();
		$("#display_titel").html(lang_2);
	}
	else{
		dis_title = '';
	}
	$("#display_titel").html(dis_title);
	$("#display_titel").css({"background-color": bg_color,"color": font_color,"font-size":font_size+"px" });
}
</script>