<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'table','controller'=>'tablegroup','action'=>'add'));
	$url_edit = $this->url(array('module'=>'table','controller'=>'tablegroup','action'=>'edit'));
	$rows = $this->rs;
	//print_r($row);exit();
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TABLE_GROUP")?>
				</div>
				<div class="tools">
					<a href="<?php echo $url;?>"><button type="button" name="btnsave" class="btn btn-primary"><i class="icon-plus"></i> <?php echo $tr->translate("ADD_NEW")?> </button></a>
				</div>
			</div>
			<div class="portlet-body" class="col-md-12">
			<div class="dataTables_wrapper no-footer" id="sample_6_wrapper">
				<table aria-describedby="sample_6_info" role="grid" class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_6">
						<thead>
							 <tr role="row">
							   <th data-column-index="0" aria-label="Rendering engine" colspan="1" rowspan="1" class="sorting_asc" aria-sort="ascending">
									TABLE_GROUP_CODE
							   </th>
							   <th data-column-index="1" aria-label="Browser: activate to sort column ascending" aria-sort="ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="sorting_asc">
								    DESCRIPTION
							   </th>
							   <th data-column-index="2" aria-label="Platform(s): activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								 	DESCRIPTION1
								</th>
								<th data-column-index="3" aria-label="Engine version: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								    DESCRIPTION2
								</th>
								<th data-column-index="3" aria-label="Engine version: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								    NOTE
								</th>
								<th data-column-index="3" aria-label="Engine version: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								    STATUS
								</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($rows as $row){?>
							<tr class="odd" role="row">
							     <?php if ($row['status']==0){
							     	      $row['status']='មិនប្រើប្រាស់';
							             }else{$row['status']='ប្រើប្រាស់';
							             }
							     ?>
								<td><?php echo $row["code"];?></td>
								<td><a href="<?php echo $url_edit ?>/id/<?php echo $row['id'];?>"><?php echo $row["description"];?></a></td>
								<td><a href="<?php echo $url_edit ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang1"];?></a></td>
								<td><a href="<?php echo $url_edit ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang2"];?></a></td>
								<td><a href="<?php echo $url_edit ?>/id/<?php echo $row['id'];?>"><?php echo $row["note"];?></a></td>
								<td><a href="<?php echo $url_edit ?>/id/<?php echo $row['id'];?>"><?php echo $row["status"];?></a></td>
							</tr>
					   <?php }?>
					</tbody>
				</table>
			</div>
		</div>
	   </div>
					<!-- END EXAMPLE TABLE PORTLET-->
  </div>
</div>
