<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'));
	$url_edit = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
									<div class="panel-body">
										
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("WAREHOUSE_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" >
													<?php echo $form->getElement('harehoust_id');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-1 control-label">
												</label>
												<div class="col-sm-11">
													<?php echo $form->getElement('har_id');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("Date")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" class="input-group" >
												   <?php echo $form->getElement('date');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SESSION")?>#
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('session');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label">
													<?php echo $tr->translate("REFERENCE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-10" class="input-group" >
												   <?php echo $form->getElement('referent');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" class="input-group" >
												   <?php echo $form->getElement('item_code');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-1 control-label">
												</label>
												<div class="col-sm-11" class="input-group" >
												   <?php echo $form->getElement('item_code');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("BARCODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" class="input-group" >
												   <?php echo $form->getElement('barcode');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ADJUSLING_FACTOR")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" class="input-group" >
												   <?php echo $form->getElement('adjus_factor');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-1 control-label">
												</label>
												<div class="col-sm-11" class="input-group" >
												   <?php echo $form->getElement('adjus_factors');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ON_HAND")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8" class="input-group" >
												   <?php echo $form->getElement('on_hand');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-1 control-label">
												</label>
												<div class="col-sm-11" class="input-group" >
												   <?php echo $form->getElement('on_hands');?>
												</div>
											</div>
										</div>
										<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>OLD QTY</th>
																<th>NEW QTY</th>
															</tr>
														</thead>
													</table>
												</div>
											</div>
										</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>