<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'));
	$url_edit = $this->url(array('module'=>'inventory','controller'=>'measure','action'=>'add'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
						<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("UNIT_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('unit_ID');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SECOND_LANGUAGE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('second_language');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("COLOR")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('color');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("APPLY_TO_COMPANY")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('apply_company');?>
												</div>
											</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label">
													<?php echo $tr->translate("NOTE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-10">
													<?php echo $form->getElement('note');?>
												</div>
											</div>
										</div>
										</div>
										<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>WHREE_HOUSE_ID</th>
																<th class="hidden-xs">DISCRIPTION</th>
																<th>SECOND_LANGAUGE</th>
																<th>FOCOLOR</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>CASE12</td>
																<td> CASE12</td>
																<td></td>
																<td>1200</td>
															</tr>
															<tr>
																<td>CASE6</td>
																<td> CASE6</td>
																<td></td>
																<td>100</td>
															</tr>
															<tr>
																<td>UNIT</td>
																<td> UNIT</td>
																<td></td>
																<td>600</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>