<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="#" id="form_sample_2" class="form-horizontal" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("WHERE_HOUSE_ID")?><span class="required"></span>
							</label>
							<div class="input-icon right">
							<div class="col-md-4">
								<div class="input-icon right">
												<i class="fa"></i>
									<?php echo $form->getElement('where_house_id');?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("DESCRIPTION")?>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa"></i>
									<?php echo $form->getElement('description');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SECOUND_LANGUAGE")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('second_language');?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("ADDRESS1")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('address1');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("ADDRESS2")?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa"></i>
									<?php echo $form->getElement('address2');?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("PHONE")?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa"></i>
									<?php echo $form->getElement('phone');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("FAX")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('fax');?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("LOCATION_TYPE")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('location_type');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("NOTE")?><span class="required"></span>
							</label>
							<div class="col-md-8">
								<div class="input-icon right"><i class="fa"></i>
									<?php echo $form->getElement('note');?>
								</div>
							</div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>