<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'timecharge','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'timecharge','action'=>'edit'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TIME_CHARGE")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							
						    <div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("INTERVAL_TIME")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('demo3');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("EXECUTE_NUMBER")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('demo3');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
										    
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("AMOUNT_TO_CHARGE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('demo3');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("FREE_AMT")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('demo3');?>
												</div>
											</div>
										</div>
									    <div class="col-sm-12" style="padding:0px;">
									         <div class="col-sm-9" style="float: right;">
									            <button class="btn btn-info" type="submit"  name="add">ADD</button>
									            <button class="btn btn-info" type="submit"  name="update">UPDATE</button>
									            <button class="btn btn-info" type="submit"  name="delete">DELETE</button>
									            <button class="btn btn-info" type="submit"  name="move_up">MOVE_UP</button>
									            <button class="btn btn-info" type="submit"  name="move_down">MOVE_DOWN</button>
									            <button class="btn btn-info" type="submit"  name="apply_to_table">APPLY_TO_TABLE</button>
									            <button class="btn btn-info" type="submit"  name="apply_to_menu">APPLY_TO_MENU</button>
									         </div>
									    </div>
						</div>
						</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/table/timecharge/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>