<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'table','controller'=>'timecharge','action'=>'add'));
	$url_edit = $this->url(array('module'=>'table','controller'=>'timecharge','action'=>'edit'));
	$rs=$this->rs;
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TABLE_TYPE")?>
				</div>
				<div class="tools">
									            <button class="btn btn-info" type="submit"  name="move_up">MOVE_UP</button>
									            <button class="btn btn-info" type="submit"  name="move_down">MOVE_DOWN</button>
									            <button class="btn btn-info" type="submit"  name="apply_to_table">APPLY_TO_TABLE</button>
									            <button class="btn btn-info" type="submit"  name="apply_to_menu">APPLY_TO_MENU</button>
					<a href="<?php echo $url;?>"><button type="button" name="btnsave" class="btn btn-primary"><i class="icon-plus"></i> <?php echo $tr->translate("ADD_NEW")?> </button></a>
					<a href="<?php echo $url_edit;?>"><button type="submit" class="btn btn-primary" ><i class="icon-pencil"></i> <?php echo $tr->translate("EDIT")?></button></a>
					<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("DELETE")?></button></a>
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-bordered table-hover" id="sample_6">
							<thead style="background: rgb(161, 159, 159) none repeat scroll 0% 0%;">
							 <tr role="row">
							   <th>No</th>
							   <th data-column-index="0" aria-label="Rendering engine" colspan="1" rowspan="1" class="sorting_disabled">
									DESCRIPTION
							   </th>
							   <th data-column-index="1" aria-label="Browser: activate to sort column ascending" aria-sort="ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="sorting_asc">
								    EXECUTE_AMOUNT
							   </th>
							   <th data-column-index="1" aria-label="Browser: activate to sort column ascending" aria-sort="ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="sorting_asc">
								    FEE_CHARGE
							   </th>
							   <th data-column-index="2" aria-label="Platform(s): activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								 	TIME_INTERVAL
								</th>
								<th data-column-index="3" aria-label="Engine version: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								    FREE_AMOUNT
								</th>
								<th data-column-index="4" aria-label="CSS grade: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
									CHILD
								</th>
								<th data-column-index="4" aria-label="CSS grade: activate to sort column ascending"  colspan="1" rowspan="1" aria-controls="sample_6" tabindex="0" class="hidden-xs sorting">
								   MULT_TO_GUEST
								</th>
							</tr>
						</thead>
							<tbody>
							<?php foreach ($rs as $row) {?>
							    <tr class="odd" role="row">
							    <td> <?php echo $row["id"];?></td>
								<td> <?php echo $row["description"];?></td>
								<td><?php echo $row["execute_amount"];?></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["fee_charge"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["time_interval"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["free_amount"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["chil_per"];?></a></td>
								<td><a href="<?php echo $url_edit;?>/id/<?php echo $row['id'];?>"><?php echo $row["nul_mul"];?></a></td>
							</tr>
							<?php }?>
							</tbody>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
	</div>
