<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('item_code');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SUPPLIER_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('supplier_id');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("PART_NUMBER")?>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('part_number');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;margin-top: 100px;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable" style="margin-top: -100px;" id="tabShwo">
														<ul id="myTab" class="nav nav-tabs">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																	
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("SUPPLIER_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example4" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
														<div class="tab-content">
															<div class="tab-pane fade in active" id="myTab_example1" class="col-sm-12">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
										                          	<div class="form-group col-sm-6">
											                          	<label class="col-sm-4 control-label">
												                        	<?php echo $tr->translate("LEAD_TIME")?> <span class="symbol required"></span>
												                        </label>
												                     <div class="col-sm-8">
													                        <?php echo $form->getElement('demo3');?>
												                     </div>
											                         </div>
											                         <div class="form-group col-sm-6">
												                          <label class="col-sm-4 control-label">
													                         <?php echo $tr->translate("MINIMUM_ORDER")?> <span class="symbol required"></span>
												                          </label>
												                      <div class="col-sm-8">
													                         <?php echo $form->getElement('demo3');?>
												                      </div>
											                         </div>
										                         </div>
										                         <div class="col-sm-12" style="padding: 0;">
										                          	<div class="form-group col-sm-6">
											                          	<label class="col-sm-4 control-label">
												                        	<?php echo $tr->translate("PURCHASE_DESCOUNT")?>
												                        </label>
												                     <div class="col-sm-8">
													                        <?php echo $form->getElement('demo3');?>
												                     </div>
											                         </div>
											                         <div class="form-group col-sm-6">
												                          <label class="col-sm-4 control-label">
													                         <?php echo $tr->translate("ON_ORDER ")?> <span class="symbol required"></span>
												                          </label>
												                      <div class="col-sm-8">
													                         <?php echo $form->getElement('on_order');?>
												                      </div>
											                         </div>
										                         </div>
										                         <div class="col-sm-12" style="padding: 0;">
										                          	<div class="form-group col-sm-6">
											                          	<label class="col-sm-4 control-label">
												                        	<?php echo $tr->translate("LAST_COST")?> <span class="symbol required"></span>
												                        </label>
												                     <div class="col-sm-8">
													                        <?php echo $form->getElement('last_cost');?>
												                     </div>
											                         </div>
											                         <div class="form-group col-sm-6">
												                          <label class="col-sm-4 control-label">
													                         <?php echo $tr->translate("TOTAL_RECEIPT")?> <span class="symbol required"></span>
												                          </label>
												                      <div class="col-sm-8">
													                         <?php echo $form->getElement('totale_re');?>
												                      </div>
											                         </div>
										                         </div>
										                         <div class="col-sm-12" style="padding: 0;">
										                          	<div class="form-group col-sm-6">
											                          	<label class="col-sm-4 control-label">
												                        	<?php echo $tr->translate("LAST_RECEIVE_DATE")?> <span class="symbol required"></span>
												                        </label>
												                     <div class="col-sm-8">
													                        <?php echo $form->getElement('last_re');?>
												                     </div>
											                         </div>
										                         </div>
										                            <div class="col-sm-12">
												                      	<div class="tabbable"  id="tabShwo" style="border: 1px;">
												                      	      <div class="col-sm-12" style="padding: 0;">
											                                     <div class="form-group col-sm-6">
												                                     <label class="col-sm-4 control-label">
												                                       <input type="radio" class="grey" name="optionsRadios" value="1"
													                                  style="position: absolute; top: -10%; left: -10%; display: block; width: 120%; height: 120%;
                                                                                      margin: 0px; padding: 0px; background: none repeat scroll 0% 0% rgb(255, 255, 255); border: 0px none; opacity: 0;" >
													                                     <?php echo $tr->translate("PERCENTAGE")?>  <span class="symbol required"></span>
												                                    </label>
												                                    <div class="col-sm-8">
													                                     <?php echo $form->getElement('percending');?>
												                                    </div>
											                                     </div>
											                                     <div class="form-group col-sm-6" style="padding-left: 10px; ">
												                                     <label class="col-sm-4 control-label">
												                                       <input type="radio" class="grey" name="optionsRadios" value="2"
													                                  style="position: absolute; top: -10%; left: -10%; display: block; width: 120%; height: 120%;
                                                                                      margin: 0px; padding: 0px; background: none repeat scroll 0% 0% rgb(255, 255, 255); border: 0px none; opacity: 0;" >
													                                     <?php echo $tr->translate("AMOUNT")?>  <span class="symbol required"></span>
												                                    </label>
												                                    <div class="col-sm-8">
													                                     <?php echo $form->getElement('amount');?>
												                                    </div>
											                                     </div>
										                                       </div>
												                      	</div>
												                    </div>
															</div>
															</div>
															<div class="tab-pane fade" id="myTab_example2">
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("FORMART")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('demo4');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("SETTING")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('setting');?>                                                
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("ARRANGE")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('arrange');?>                                                
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("RESIZE")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('resize');?>                                                
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example4">
																<div class="form-group">																	<br />
																	<div class="col-sm-12">
																		<?php echo $form->getElement('note');?>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										
										</div>
										<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("NUM")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("MENU_GROUP_CODE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("DESCRIPTION")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_ONE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_TWO")?></th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td style="text-align: center;">1</td>
																<td>Amaya</td>
																<td class="hidden-xs">W3C,
																INRIA</td>
																<td>Free</td>
																<td class="hidden-xs">W3C</td>
															</tr>
															<tr>
																<td style="text-align: center;">2</td>
																<td>AOL Explorer</td>
																<td class="hidden-xs">America Online, Inc</td>
																<td>Free</td>
																<td class="hidden-xs">Proprietary</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>