<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'table','controller'=>'tabletype','action'=>'edit'));
	$url_save_close = $this->url(array('module'=>'table','controller'=>'tabletype','action'=>'edit'));
?>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TABLES_TYPE")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" >
				<div class="form-body">
				     <div  class="col-sm-12"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-3 control-label" >
													<?php echo $tr->translate("TABLE_TYPE_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-9">
													<?php echo $form->getElement('type_code');?>
													<?php echo $form->getElement('id');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-3 control-label" >
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-9">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-3 control-label">
													<?php echo $tr->translate("DESCRIPTION1")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-9">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-3 control-label">
													<?php echo $tr->translate("DESCRIPTION2")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-9">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-3 control-label">
													<?php echo $tr->translate("NOTE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-12">
													<?php echo $form->getElement('note');?>
												</div>
											</div>
											
				     </div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<a href="<?php echo $url_save_close;?>"><button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></a>
								<a href="<?php echo $this->baseUrl();?>/table/tabletype/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
