<?php 	$tr=Application_Form_FrmLanguages::getCurrentlanguage();?> 
<?php $request=Zend_Controller_Front::getInstance()->getRequest(); $module=$request->getModuleName();?>
<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
			<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
			<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
			<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="start ">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">Dashboard</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="index.html">
							<i class="icon-bar-chart"></i>
							Default Dashboard</a>
						</li>
						<li>
							<a href="index_2.html">
							<i class="icon-bulb"></i>
							New Dashboard #1</a>
						</li>
						<li>
							<a href="index_3.html">
							<i class="icon-graph"></i>
							New Dashboard #2</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("MENU_MANAGERMENT")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/group">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("MENU_GROUP")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/item">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("MENU_ITEM")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/arrangement">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("MENU_ARRANGEMENT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/combo">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("COMBO_MASTER")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/recipe">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("RECIPE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/discount">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("DISCOUNT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/menu/happyhour">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("HAPPY_HOUR")?></a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("TABLE_MANAGERMENT")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/index">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("APPLY_CUSTOMER")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/tables">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TABLES")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/arrangement">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TABLE_ARRANGEMENT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/tablegroup">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TABLE_GROUP")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/tabletype">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TABLE_TYPE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/timecharge">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TIME_CHARGE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/unlockservice">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("UNLOCK_SERVICE")?></a>
						</li>
						
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/unlocktable">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("UNLOCK_TABLE")?></a>
						</li>
						
						<li>
							<a href="<?php echo $this->baseUrl()?>/table/tableservice">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("SERVICE")?></a>
						</li>
					</ul>
				</li>
				
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("INVENTORY_MANAGERMENT")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/wherehouse">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("WHERE_HOUSE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/measure">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("MEASURE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/productlind">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("PRODUCTLIND")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/master">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("MASTER")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/supplier">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("SUPPLIER")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/color">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("COLOR")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/location">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("LOCATION")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/receive">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("RECEIVE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/issue">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("ISSUE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/transferitems">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("TRANSFERITEMS")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/inventory/stockadjustment">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("STOCKADJUSTMENT")?></a>
						</li>
						
						
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("CUSTOMER_MANAGERMENT")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/deposit">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("APPLY_CREDIT_DEPOSIT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/credit">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("CREDIT_CARD")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/customer">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("CUSTOMER")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/currency">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("CURRENCY")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/currencytype">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("CURRENCY_TYPE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/cash">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("ENTER_CASH_DEPOSIT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/invoice">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("INVOICE_PAYMENT")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/exchangerate">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("EXCHANGE_RATE")?></a>
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/customer/sale">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("SALE_REPRESENTATIVE")?></a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-puzzle"></i>
					<span class="title">Report Management</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="components_pickers.html">
							Login Form</a>
						</li>
						<li>
							<a href="components_dropdowns.html">
							Registration Form</a>
						</li>
						<li>
							<a href="components_form_tools.html">
							Forgot Password Form</a>
						</li>
						<li>
							<a href="components_editors.html">
							Lock Screen</a>
						</li>
						
					</ul>
				</li>
				
				<li>
				<a href="javascript:;">
					<i class="icon-screen-desktop"></i>
					<span class="title"><?php echo $tr->translate("System Setting")?></span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/backup">
							<i class="icon-arrow-right"></i>
							<?php echo $tr->translate("BACKUP DATA")?></a>
						</li>
						<li>
						    <a href="<?php echo $this->baseUrl()?>/setting/changekey">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("CHANGE_KEY")?></a>		
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/company">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("COMPANY_SETTINGS")?>
							</a>	
						</li>
						<li>
                         <a href="<?php echo $this->baseUrl()?>/setting/costchange">
                            <i class="icon-arrow-right"></i>
					        <?php echo $tr->translate("COST_CHANGE")?>
                            </a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/export">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("EXPORT_DATA")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/head">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("HEAD_OFFICE_COMPANY_SETTING")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/import">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("IMPORT_DATA")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/payment">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("PAYMENT_TYPE")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/restore">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("RESTORE_DATA")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/select">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("SELECT_POS_COMPANY")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/station">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("STATION_SETTING")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/user">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("STATION_USER")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/unlock">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("UNLOCK_USER")?></a>	
						</li>
						<li>
							<a href="<?php echo $this->baseUrl()?>/setting/void">
							<i class="icon-arrow-right"></i>
					    	<?php echo $tr->translate("VOID_DAY_TRANSACTION")?></a>	
						</li>
						<li>
							<a href="components_editors.html">
							Payment Type</a>
						</li>
						<li>
							<a href="components_editors.html">
							Restore Data</a>
						</li>
						<li>
							<a href="components_editors.html">
							Select POS Company</a>
						</li>
						<li>
							<a href="components_editors.html">
							Station Setting</a>
						</li>
						<li>
							<a href="components_editors.html">
							System User</a>
						</li>
						
						
					</ul>
			
				
			
				<li>
					<a href="javascript:;">
					<i class="icon-briefcase"></i>
					<span class="title">Data Tables</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="table_basic.html">
							Basic Datatables</a>
						</li>
						<li>
							<a href="table_responsive.html">
							Responsive Datatables</a>
						</li>
						<li>
							<a href="table_managed.html">
							Managed Datatables</a>
						</li>
						<li>
							<a href="table_editable.html">
							Editable Datatables</a>
						</li>
						<li>
							<a href="table_advanced.html">
							Advanced Datatables</a>
						</li>
						<li>
							<a href="table_ajax.html">
							Ajax Datatables</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-wallet"></i>
					<span class="title">Portlets</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="portlet_general.html">
							General Portlets</a>
						</li>
						<li>
							<a href="portlet_general2.html">
							<span class="badge badge-roundless badge-danger">new</span>New Portlets #1</a>
						</li>
						<li>
							<a href="portlet_general3.html">
							<span class="badge badge-roundless badge-danger">new</span>New Portlets #2</a>
						</li>
						<li>
							<a href="portlet_ajax.html">
							Ajax Portlets</a>
						</li>
						<li>
							<a href="portlet_draggable.html">
							Draggable Portlets</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-bar-chart"></i>
					<span class="title">Charts</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="charts_amcharts.html">
							amChart</a>
						</li>
						<li>
							<a href="charts_flotcharts.html">
							Flotchart</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-docs"></i>
					<span class="title">Pages</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="page_timeline.html">
								<i class="icon-paper-plane"></i>
								<span class="badge badge-warning">2</span>
								New Timeline
							</a>
						</li>
						<li>
							<a href="page_todo.html">
							<i class="icon-check"></i>
							Todo</a>
						</li>
						<li>
							<a href="inbox.html">
							<i class="icon-envelope"></i>
							<span class="badge badge-danger">4</span>Inbox</a>
						</li>
						<li>
							<a href="extra_profile.html">
							<i class="icon-user-following"></i>
							<span class="badge badge-success badge-roundless">new</span>New User Profile</a>
						</li>
						<li>
							<a href="extra_profile_old.html">
							<i class="icon-user"></i>
							Old User Profile</a>
						</li>
						<li>
							<a href="extra_faq.html">
							<i class="icon-question"></i>
							FAQ</a>
						</li>
						<li>
							<a href="page_calendar.html">
							<i class="icon-calendar"></i>
							<span class="badge badge-danger">14</span>Calendar</a>
						</li>
						<li>
							<a href="page_timeline_old.html">
							<i class="icon-clock"></i>
							<span class="badge badge-info">4</span>Old Timeline</a>
						</li>
						<li>
							<a href="page_coming_soon.html">
							<i class="icon-flag"></i>
							Coming Soon</a>
						</li>
						<li>
							<a href="page_blog.html">
							<i class="icon-speech"></i>
							Blog</a>
						</li>
						<li>
							<a href="page_blog_item.html">
							<i class="icon-link"></i>
							Blog Post</a>
						</li>
						<li>
							<a href="page_news.html">
							<i class="icon-eye"></i>
							<span class="badge badge-success">9</span>News</a>
						</li>
						<li>
							<a href="page_news_item.html">
							<i class="icon-bell"></i>
							News View</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-present"></i>
					<span class="title">Extra</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="page_about.html">
							About Us</a>
						</li>
						<li>
							<a href="page_contact.html">
							Contact Us</a>
						</li>
						<li>
							<a href="extra_search.html">
							Search Results</a>
						</li>
						<li>
							<a href="extra_invoice.html">
							Invoice</a>
						</li>
						<li>
							<a href="page_portfolio.html">
							Portfolio</a>
						</li>
						<li>
							<a href="extra_pricing_table.html">
							Pricing Tables</a>
						</li>
						<li>
							<a href="extra_404_option1.html">
							404 Page Option 1</a>
						</li>
						<li>
							<a href="extra_404_option2.html">
							404 Page Option 2</a>
						</li>
						<li>
							<a href="extra_404_option3.html">
							404 Page Option 3</a>
						</li>
						<li>
							<a href="extra_500_option1.html">
							500 Page Option 1</a>
						</li>
						<li>
							<a href="extra_500_option2.html">
							500 Page Option 2</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-folder"></i>
					<span class="title">Multi Level Menu</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="javascript:;">
							<i class="icon-settings"></i> Item 1 <span class="arrow"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="javascript:;">
									<i class="icon-user"></i>
									Sample Link 1 <span class="arrow"></span>
									</a>
									<ul class="sub-menu">
										<li>
											<a href="#"><i class="icon-power"></i> Sample Link 1</a>
										</li>
										<li>
											<a href="#"><i class="icon-paper-plane"></i> Sample Link 1</a>
										</li>
										<li>
											<a href="#"><i class="icon-star"></i> Sample Link 1</a>
										</li>
									</ul>
								</li>
								<li>
									<a href="#"><i class="icon-camera"></i> Sample Link 1</a>
								</li>
								<li>
									<a href="#"><i class="icon-link"></i> Sample Link 2</a>
								</li>
								<li>
									<a href="#"><i class="icon-pointer"></i> Sample Link 3</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="javascript:;">
							<i class="icon-globe"></i> Item 2 <span class="arrow"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#"><i class="icon-tag"></i> Sample Link 1</a>
								</li>
								<li>
									<a href="#"><i class="icon-pencil"></i> Sample Link 1</a>
								</li>
								<li>
									<a href="#"><i class="icon-graph"></i> Sample Link 1</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="#">
							<i class="icon-bar-chart"></i>
							Item 3 </a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-user"></i>
					<span class="title">Login Options</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="login.html">
							Login Form 1</a>
						</li>
						<li>
							<a href="login_2.html">
							Login Form 2</a>
						</li>
						<li>
							<a href="login_3.html">
							Login Form 3</a>
						</li>
						<li>
							<a href="login_soft.html">
							Login Form 4</a>
						</li>
						<li>
							<a href="extra_lock.html">
							Lock Screen 1</a>
						</li>
						<li>
							<a href="extra_lock2.html">
							Lock Screen 2</a>
						</li>
					</ul>
				</li>
				<li class="heading">
					<h3 class="uppercase">More</h3>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-logout"></i>
					<span class="title">Quick Sidebar</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="quick_sidebar_push_content.html">
							Push Content</a>
						</li>
						<li>
							<a href="quick_sidebar_over_content.html">
							Over Content</a>
						</li>
						<li>
							<a href="quick_sidebar_over_content_transparent.html">
							Over Content & Transparent</a>
						</li>
						<li>
							<a href="quick_sidebar_on_boxed_layout.html">
							Boxed Layout</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="javascript:;">
					<i class="icon-envelope-open"></i>
					<span class="title">Email Templates</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="email_newsletter.html">
							Responsive Newsletter<br>
							Email Template</a>
						</li>
						<li>
							<a href="email_system.html">
							Responsive System<br>
							Email Template</a>
						</li>
					</ul>
				</li>
				<li class="last ">
					<a href="javascript:;">
					<i class="icon-pointer"></i>
					<span class="title">Maps</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="maps_google.html">
							Google Maps</a>
						</li>
						<li>
							<a href="maps_vector.html">
							Vector Maps</a>
						</li>
					</ul>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->