<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'table','controller'=>'tables','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<style>
      
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TABLES")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" >
				<div class="form-body">
				     <div  style="margin-left: -90px;" class="col-sm-10">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("MENU_GROUP_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('menu_code');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
				     </div>
					 <div style="" class="col-sm-2" >
					             <div >
											<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											</div>
											<div>
												<span class="btn default btn-file">
												<span class="fileinput-new">
												Select image </span>
												<span class="fileinput-exists">
												Change </span>
												<input type="file" name="fileinput" value="">
												</span>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
									</div>
								</div>
						 </div>   
					 </div>		
					 		<div class="col-sm-12" style=";margin-top: 100px;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable" style="margin-top: -100px; " id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background:#7C9BAB 0px; ">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																	
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("FORMAT")?>
																</a>
															</li>
															
															<li>
																<a href="#myTab_example3" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
								<div class="tab-content">
									<div class="tab-pane fade in active" id="myTab_example1" class="col-sm-12">
										<div class="form-group">
							               <div  style="margin-left: -90px;" class="col-sm-8">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("GROUP_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('g_code');?>
												</div>
											</div>
											<div class="form-group col-sm-12" >
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SHOW_DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("MAX_SEAT")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
												<div id="spinner1">
												<div class="input-group" >
													<?php echo $form->getElement('max_seat');?>
													<div class="spinner-buttons input-group-btn btn-group-vertical">
														<button type="button" class="btn spinner-up btn-xs blue">
														<i class="fa fa-angle-up"></i>
														</button>
														<button type="button" class="btn spinner-down btn-xs blue">
														<i class="fa fa-angle-down"></i>
														</button>
													</div>
												</div>
											    </div>
												</div>
											</div>
											<div class="form-group col-sm-12" style="margin-left:90px;">
											<table style="width: 80%;margin-left: 30px;">
											   <tr>
											   <td class="col-sm-2"><?php echo $tr->translate("PRICE")?></td>
											   <td>
											    <div id="spinner3">
												<div class="input-group" >
													<?php echo $form->getElement('price');?>
													<div class="spinner-buttons input-group-btn">
														<button type="button" class="btn spinner-up default">
														<i class="fa fa-angle-up"></i>
														</button>
														<button type="button" class="btn spinner-down default">
														<i class="fa fa-angle-down"></i>
														</button>
													</div>
												  </div>
											     </div>
												</td>
											   <td class="col-sm-2"><?php echo $tr->translate("EST_TIME")?></td>
											   <td >
											          <div class="col-md-5">
											<div class="input-group">
												<?php echo $form->getElement('est_time');?>
												<span class="input-group-btn">
												<button class="btn default" type="button" id="clockface_2_toggle"><i class="fa fa-clock-o"></i></button>
												</span>
											</div>
										</div>
											   </td>
											   </tr>
											</table>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("APPLY_TO_COMPANY")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description2');?>
												</div>
											</div>
											<div class="form-group col-sm-12" style="margin-left:90px;">
											 <table>
											    <tr>
											    <td ><?php echo $form->getElement('active');?></td><td><?php echo $tr->translate("ACTIVE")?> </td>
											    <td class="col-sm-1"></td>
											    <td ><?php echo $form->getElement('time_ck');?></td><td><?php echo $tr->translate("TIME")?> </td>
											    <td class="col-sm-1"></td>
											    <td ><?php echo $form->getElement('dicount_ck');?></td><td><?php echo $tr->translate("DISCOUNT")?> </td>
											    <td class="col-sm-1"></td>
											    <td><input type="button" class="btn btn-primary" value="ASIGN_TABLE_TYPE" name="btn_ch"/></td>
											    </tr>
											 </table>
											</div>
				                        </div>
					                    <div style="" class="col-sm-4" >
					                    <div class="col-sm-12">
													<?php echo $form->getElement('g_code1');?>
										</div>
					                    <div class="col-md-12" >
					                    <div class="col-sm-12" style="margin-top: 20px;">
											<?php echo $tr->translate("TYPE_OF_TABLE")?> <span class="required"> </span>
										</div>
								           <div class="col-sm-12">
												<?php echo $form->getElement('type_of_table');?>
										  </div>
						 </div>   
					 </div>		
				</div>
			</div>
					<div class="tab-pane fade" id="myTab_example2">
								<div class="form-group">
												<label class="col-sm-4 control-label" for="form-field-1">
														<?php echo $tr->translate("FORMART")?>
												</label>
														<div class="col-sm-8">
																		<?php echo $form->getElement('demo4');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("SETTING")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('setting');?>                                                
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("ARRANGE")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('arrange');?>                                                
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-4 control-label" for="form-field-1">
																		<?php echo $tr->translate("RESIZE")?>
																	</label>
																	<div class="col-sm-8">
																		<?php echo $form->getElement('resize');?>                                                
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example3">
																<div class="form-group">																	<br />
																	<div class="col-sm-12">
																		<?php echo $form->getElement('note');?>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
										</div>
							</div>			
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<a href="<?php echo $url_save;?>"><button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button></a>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/table/tables/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
