<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'table','controller'=>'tables','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<title><?php echo $tr->translate("TABLES")?></title>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TABLES")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" >
				<div class="form-body">
				     <div  class="col-sm-9"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("TABLE_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('table_code');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
				     </div>
					 <div style="" class="col-sm-3" >
					             <div >
											<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<label id="display_titel" class="full-size">
													<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" style="padding:3px ;background:#7C9BAB none repeat scroll 3px;"/>
												</label>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											
											</div>
											<div>
												<?php echo $form->getElement('photo');?>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
									</div>
								</div>
						 </div>   
					 </div>		
					 		<div class="col-sm-12" style=";margin-top: 100px;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable" style="margin-top: -100px; " id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background:#7C9BAB 0px; ">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																	
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("FORMAT")?>
																</a>
															</li>
															
															<li>
																<a href="#myTab_example3" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
								<div class="tab-content">
									<div class="tab-pane fade in active" id="myTab_example1" class="col-sm-12">
										<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("GROUP_CODE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right" >
													<i class="fa"></i>
													<?php echo $form->getElement('group_code');?>
												</div>
											</div>
											<label class="control-label col-md-2"><?php echo $tr->translate("TYPE_OF_TABLE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('type_of_table');?>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("SHOW_DESCRIPTION")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											 <label class="control-label col-md-2"><?php echo $tr->translate("PRICE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
													<?php echo $form->getElement('price');?>
											</div>
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("MAX_SEAT")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												
															<?php echo $form->getElement('max_seat');?>
											</div>
											<label class="control-label col-md-2"><?php echo $tr->translate("EST_TIME")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
														    <?php echo $form->getElement('est_time');?>
											</div>
                                  	</div>
                                  	<div class="form-group">
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("APPLY_TO_COMPANY")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('apply_to_company');?>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
                                  	  <div class=" col-md-6">
										           <div class="col-md-1"><?php echo $form->getElement('active');?></div>
										           <label class="col-md-3"><?php echo $tr->translate("ACTIVE")?></label>
										           <div class="col-md-1"><?php echo $form->getElement('time_ck');?></div>
										           <label class="col-md-2"><?php echo $tr->translate("TIME")?></label>
										           <div class="col-md-1"><?php echo $form->getElement('dicount_ck');?></div>
										          <label class="col-md-3"><?php echo $tr->translate("DICOUNT")?></label>
									   </div>
                                  	</div>
			</div>
					<div class="tab-pane fade" id="myTab_example2">
											                   <div class="form-group">
													                 <label class="col-sm-2 control-label" for="form-field-1">
																       <?php echo $tr->translate("BACK_COLOR")?>
														       	    </label>
																   <div class="col-md-4">
																		<?php echo $form->getElement('backgroun_color');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_COLOR")?>
																	</label>
																	<div class="col-md-4">
																		<?php echo $form->getElement('font_color');?> 
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_SIZE")?>
																	</label>
																	<div class="col-sm-4">
																		<div id="spinner4">
																			<div class="input-group" >
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-up blue">
																					<i class="fa fa-plus"></i>
																					</button>
																				</div>
																				<?php echo $form->getElement('font_size');?>
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-down red">
																					<i class="fa fa-minus"></i>
																					</button>
																				</div>
																			</div>
																		</div>  
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example3">
																<div class="form-group">																	
																	<div class="col-sm-12">
																		<?php echo $form->getElement('note');?>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
										</div>
							</div>			
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<a href="<?php echo $url_save;?>"><button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button></a>
								<a href="<?php echo $url_save;?>"><button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></a>
								<a href="<?php echo $this->baseUrl();?>/table/tables/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
 <div id="dialog" title="TABLE_GROUP">
          <form  class="form-horizontal" enctype="multipart/form-data" method="post" >
				<div class=" col-sm-6" style="background: #F2E2E2;width: 100%;">
			        <div class="form-group col-sm-12">
					    <label class="col-sm-4 control-label" >
							<?php echo $tr->translate("GROUP_CODE")?> <span class="symbol required"></span>
						</label>
						<div class="col-sm-8">
							<input id="new_group_code" class="form-control input-large"  type="text" name="new_group_code" required>
						</div>
					</div>
					<div class="form-group col-sm-12">
					    <label class="col-sm-4 control-label" >
							<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
						</label>
						<div class="col-sm-8">
							<input id="new_description" class="form-control input-large"  type="text" name="new_description"  required >
						</div>
					</div>
					<div class="col-md-offset-3 col-md-9">
					    <button id="b_add" type="button" name="btnadd" class="btn btn-primary" onClick="addNew();"><i class="fa fa-save" ></i> SAVE_NEW </button>
					</div>
			  </div>
			 </form>
 </div>
 <div id="dialog1" title="TABLE_TYPE">
				  <form  class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class=" col-sm-6" style="background: #F2E2E2;width: 100%;">
				        <div class="form-group col-sm-12">
						    <label class="col-sm-4 control-label" >
								<?php echo $tr->translate("TABLE_TYPE_CODE ")?> <span class="symbol required"></span>
							</label>
							<div class="col-sm-8">
								<input class="form-control input-large"  type="text" name="new_type_code" id="new_type_code" required>
							</div>
						</div>
						<div class="form-group col-sm-12">
						    <label class="col-sm-4 control-label" >
								<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
							</label>
							<div class="col-sm-8">
								<input class="form-control input-large"  type="text" name="new_type_description" id="new_type_description" required >
							</div>
						</div>
						<div class="col-md-offset-3 col-md-9">
						    <button id="btn_add_type" type="button" name="btn_add_type" class="btn btn-primary" onClick="addNewType();"><i class="fa fa-save" ></i> SAVE_NEW </button>
						</div>
				  </div>
				 </form>
 </div>
<script>
function displayDescriptions(){
	    popup = $('#group_code').val();
	    if(popup==-1){
            $( "#dialog" ).dialog( "open" );
            $("#dialog").animate({top:"0px"},"fast");
	    }else{
	    	$( "#dialog" ).dialog( "close" );
	    	$("#dialog input[type=text]").val('');
	    }
	    
}
function popoupTableType(){
	popup=$("#type_of_table").val();
	if(popup==-1){
	   $("#dialog1").dialog("open");
	}else{
		$("#dialog1").dialog("close");
	}
}
function displayDescription(){
	/*popup = $('#group_code').val();
	type_of_table = $('#type_of_table').val();
	if(popup == -1){
		$("input").focus();
		$('#popup').show(500);
		$('#popup').animate({top:"300px"},"fast");
    }
	else if(type_of_table == -1){
		$("#popup_table_type").show(500);
		$("#popup_table_type").animate({top:"300px"},"fast");
		
	}
	else {
		$("#popup").hide(400);
		$("#popup_table_type").hide(400);
	}
	$("#b_close").click(function() {
        $("#popup").hide(400);
        $('#group_code').val("");
        $("#popup input[type=text]").val('');
        //location.reload();
    }); 
    $("#b_close_type").click(function (){
        $("#popup_table_type").hide(400);
        $('#type_of_table').val("");
        $("#popup_table_type input[type=text]").val('');
    });
	$("#b_add").click(function() {
        $("#popup input[type=text]").val('');
    }); 
	$("#btn_add_type").click(function() {
        $("#popup_table_type input[type=text]").val('');
    });
    */ 
}
function displayPhoto(){
	backgroun_color = $("#backgroun_color").val();
	font_color = $("#font_color").val();
	font_size = $("#font_size").val();
	dis_type = $("#show_description").val();
	if(dis_type==1){
		dis_title = $("#table_code").val();
	}
	else if(dis_type==2){
		dis_title = $("#description").val();
	}
	else if(dis_type ==3 ){
		dis_title = $("#lang_1").val();
		
	}
	else if(dis_type==4){
		dis_title=$("#lang_2").val();
	}
	else{
		dis_title ='';
	}
	$("#display_titel").html(dis_title);
	$("#display_titel").css({"background-color": backgroun_color,"color": font_color, "font-size": font_size+"px"});
}

var url = "<?php echo $this->url(array('module'=>'table','controller'=>'tables','action'=>'add-new'));?>";
function addNew(){
	var group_code = $('#new_group_code').val();
	var description = $('#new_description').val();
	code_des =group_code+"-"+description;
	//alert(group_code+"-"+description);
	if(group_code=="" || group_code== null){
		alert('Please input field!');
		$('input').focus();
	}else{
	 $.ajax({
         type: "POST",
         group_code: "required", 
         url: url,
         data: {'group_code':group_code,'description':description}, // serializes the form's elements.
         success: function(data)
         {   //alert(data);
             $("#dialog").hide(400);
             $('#group_code').val("");
             $("#dialog input[type=text]").val('');
             value = $.parseJSON(data);
            // alert(value['id'])
           $('#group_code').append($('<option></option>').attr('value',value['id']).attr("selected","selected").text(code_des)); 
           $("#group_code").val(value['id']).trigger('change');
           $('#group_code').trigger("liszt:updated");
         },
		 error: function(e){
			 alert(e);
		 }
       });
	}

}

var url_type = "<?php echo $this->url(array('module'=>'table','controller'=>'tables','action'=>'addtype'));?>";
function addNewType(){
	var new_type_code = $('#new_type_code').val();
	var new_type_description = $('#new_type_description').val();
	code_des=new_type_code+"-"+new_type_description;
	if(new_type_code=="" || new_type_description == null){
		alert('Please input field!');
		//$('input').focus();
	}else{
		 $.ajax({
	         type: "POST",
	         group_code: "required", 
	         url: url_type,
	         data: {'new_type_code':new_type_code,'new_type_description':new_type_description}, // serializes the form's elements.
	         success: function(data)
	         {   //alert(data);
	             $("#dialog1").hide(400);
	             $("#dialog1 input[type=text]").val('');
	             value = $.parseJSON(data);
	            // alert(value['id'])
	           $('#type_of_table').append($('<option></option>').attr('value',value['id']).attr("selected","selected").text(code_des)); 
	           $("#type_of_table").val(value['id']).trigger('change');
	           $('#type_of_table').trigger("liszt:updated");
	         },
			 error: function(e){
				 //alert(e);
			 }
	       });
		}
}
</script>