<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'table','controller'=>'tables','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("TABLES")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" >
				<div class="form-body">
				     <div  class="col-sm-9"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("TABLE_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('table_code');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" >
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_TWO")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_2');?>
												</div>
											</div>
				     </div>
					 <div style="" class="col-sm-3" >
					             <div >
											<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											</div>
											<div>
												<span class="btn default btn-file">
												<span class="fileinput-new">
												Select image </span>
												<span class="fileinput-exists">
												Change </span>
												<input type="file" name="fileinput" value="">
												</span>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
									</div>
								</div>
						 </div>   
					 </div>		
					 		<div class="col-sm-12" style=";margin-top: 100px;">
											<div class="form-group col-sm-12">
												<div class="col-sm-12">
													<div class="tabbable" style="margin-top: -100px; " id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background:#7C9BAB 0px; ">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																	
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("FORMAT")?>
																</a>
															</li>
															
															<li>
																<a href="#myTab_example3" data-toggle="tab" style="color:#0A0A0B;">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
								<div class="tab-content">
									<div class="tab-pane fade in active" id="myTab_example1" class="col-sm-12">
										<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("GROUP_CODE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('group_code');?>
												</div>
											</div>
											<label class="control-label col-md-2"><?php echo $tr->translate("TYPE_OF_TABLE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('type_of_table');?>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("SHOW_DESCRIPTION")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											 <label class="control-label col-md-2"><?php echo $tr->translate("PRICE")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<div id="spinner1">
														<div class="input-group ">
														    <?php echo $form->getElement('price');?>
															<div class="spinner-buttons input-group-btn btn-group-vertical">
																<button type="button" class="btn spinner-up btn-xs blue">
																<i class="fa fa-angle-up"></i>
																</button>
																<button type="button" class="btn spinner-down btn-xs blue">
																<i class="fa fa-angle-down"></i>
																</button>
															</div>
														</div>
													</div>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("MAX_SEAT")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<div id="spinner3">
														<div class="input-group" >
															<?php echo $form->getElement('max_seat');?>
															<div class="spinner-buttons input-group-btn">
																<button type="button" class="btn spinner-up default">
																<i class="fa fa-angle-up"></i>
																</button>
																<button type="button" class="btn spinner-down default">
																<i class="fa fa-angle-down"></i>
																</button>
															</div>
														</div>
													</div>
												</div>
											</div>
											<label class="control-label col-md-2"><?php echo $tr->translate("EST_TIME")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<div class="col-md-14">
														<div class="input-group">
														    <?php echo $form->getElement('est_time');?>
															<span class="input-group-btn">
															<button class="btn default" type="button" id="clockface_2_toggle"><i class="fa fa-clock-o"></i></button>
															</span>
														</div>
													</div>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
                                  	</div>
                                  	<div class="form-group">
							                <label class="control-label col-md-2"><?php echo $tr->translate("APPLY_TO_COMPANY")?> <span class="required">
												</span>
											</label>
											<div class="col-md-4">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $form->getElement('apply_to_company');?>
												</div>
											</div>
                                  	</div>
                                  	<div class="form-group">
                                  	  <div class=" col-md-6">
										           <div class="col-md-1"><?php echo $form->getElement('active');?></div>
										           <label class="col-md-3"><?php echo $tr->translate("ACTIVE")?></label>
										           <div class="col-md-1"><?php echo $form->getElement('time_ck');?></div>
										           <label class="col-md-2"><?php echo $tr->translate("TIME")?></label>
										           <div class="col-md-1"><?php echo $form->getElement('dicount_ck');?></div>
										          <label class="col-md-3"><?php echo $tr->translate("DICOUNT")?></label>
										          <div class="col-md-1"><button type="submit" class="btn btn-primary" ><?php echo $tr->translate("ASSING_TABLE_TYPE")?></button></div>
									   </div>
                                  	</div>
			</div>
					<div class="tab-pane fade" id="myTab_example2">
											                   <div class="form-group">
													                 <label class="col-sm-2 control-label" for="form-field-1">
																       <?php echo $tr->translate("BACK_COLOR")?>
														       	    </label>
																   <div class="col-md-4">
																		<?php echo $form->getElement('backgroun_color');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_COLOR")?>
																	</label>
																	<div class="col-md-4">
																		<?php echo $form->getElement('font_color');?> 
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_SIZE")?>
																	</label>
																	<div class="col-sm-4">
																		<div id="spinner4">
																			<div class="input-group" >
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-up blue">
																					<i class="fa fa-plus"></i>
																					</button>
																				</div>
																				<?php echo $form->getElement('font_size');?>
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-down red">
																					<i class="fa fa-minus"></i>
																					</button>
																				</div>
																			</div>
																		</div>  
																	</div>
																</div>
															</div>
															<div class="tab-pane fade" id="myTab_example3">
																<div class="form-group">																	
																	<div class="col-sm-12">
																		<?php echo $form->getElement('note');?>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
										</div>
							</div>			
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<a href="<?php echo $url_save;?>"><button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button></a>
								<a href="<?php echo $url_save;?>"><button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></a>
								<a href="<?php echo $this->baseUrl();?>/table/tables/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
