<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'group','action'=>'index'),null,true);
?>
<form action="#" id="form_sample_2" class="form-horizontal">
								<div class="form-body">
									<div class="alert alert-danger display-hide">
										<button class="close" data-close="alert"></button>
										You have some form errors. Please check below.
									</div>
									<div class="alert alert-success display-hide">
										<button class="close" data-close="alert"></button>
										Your form validation is successful!
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Name <span class="required">
										* </span>
										</label>
										<div class="col-md-4">
											<div class="input-icon right">
												<i class="fa"></i>
												<input type="text" class="form-control" name="name"/>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Name <span class="required">
										* </span>
										</label>
										<div class="col-md-4">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $form->getElement('menu_code');?>
											</div>
										</div>
									</div>
									<div class="col-md-4">
											<div class="input-icon right">
												<i data-original-title="This field is required." class="fa fa-warning"></i>
												<input aria-invalid="true" aria-describedby="number-error number-error" aria-required="true" class="form-control" name="number" type="text">
											</div>
										</div>
									
									
									
								</div>
								<div class="form-actions">
									<div class="row">
										<div class="col-md-offset-3 col-md-9">
											<button type="submit" class="btn green">Submit</button>
											<button type="button" class="btn default">Cancel</button>
										</div>
									</div>
								</div>
							</form>