<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'customer','controller'=>'invoice','action'=>'add'));
?>
<title><?php echo $tr->translate("INVOICE_PAYMENT")?></title>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("INVOICE_PAYMENT")?>
				</div>
			</div>
			<div class="portlet-body form"  >
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" action="<?php echo $url_save;?>" >
				<div class="form-body">
				     <div  class="col-sm-12"  >
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("CUSTOMER_ID ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('customer_id');?>
												</div>
												<label class="col-sm-1 control-label" >
													<?php echo $tr->translate(" ")?> 
												</label>
												<div class="col-sm-5">
													<?php echo $form->getElement('general');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("CONTACT_NAME  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('contact_name');?>
												</div>
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("SESSION  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('session');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("PHONE  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('phone');?>
												</div>
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("CHECK_REF   ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('check');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("FAX  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('fax');?>
												</div>
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("PAY_DATE  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('pay_date');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("ADDRESS  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('address');?>
												</div>
												<label class="col-sm-1 control-label" >
													<?php echo $tr->translate(" ")?> 
												</label>
												<div class="col-sm-5">
													<?php echo $form->getElement('address1');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("ACCONT_NO ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('account_no');?>
												</div>
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("PAY_AMOUNT  ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('pay_amount');?>
												</div>
											</div>
											<div class="form-group col-sm-12">
												<div class="col-sm-6">
												<button type="button" class="btn default btn-lg"><?php echo $tr->translate("AUTO_APPLY  ")?></button>
												<button type="button" class="btn default btn-lg"><?php echo $tr->translate("MANUAL_APPLY  ")?></button>
												</div>
												<label class="col-sm-2 control-label" >
													<?php echo $tr->translate("REMAINING_AMOUNT ")?> 
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('remaining_amount');?>
												</div>
											</div>
				     </div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="btnsave_close" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/customer/invoice/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
