<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url_save = $this->url(array('module'=>'customer','controller'=>'credit','action'=>'add'));
?>
<title><?php echo $tr->translate("CREDIT_CARD");?></title>
<style>
.form-horizontal .control-label {
       text-align: left; 
}
.form-horizontal .form-group {
    margin-left: 0px;
    margin-right: 0px;
}
.form .form-actions {
    border-top: 0px;
}
 a{
    color:black;
}
</style>
<div class="row"> 
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("CREDIT_CARD")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post" action="<?php echo $url_save; ?>">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CUSTOMER_ID")?> 
							<span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('customer_id');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("APPLY_TOCOMPANY")?> 
							<span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('apply');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COMPANY")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('company');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("CURRENT_BALANCE")?> <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('current');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CONTACT_NAME")?>  <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('contact');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("YTD_SALE")?>  <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('sale');?>
								</div>
							</div>
							</div>
							<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("MOBILE_PHONE")?> 
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('mobile');?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("AVILABLE_CREDIT")?> <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('credit');?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CUSTOMER_GROUP_ID")?> 
							<span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('cus_id');?>
								</div>
							</div>
							
						
						<div class="form-group col-sm-6">
													<label class="col-sm-4 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("IN_ACTIVE")?><span class="symbol required"></span>
													</label>
													<div class="col-sm-2">
														<label class="checkbox-inline">
															<?php echo $form->getElement('active');?>
														</label>													
													</div>
													<label class="col-sm-4 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("ON_HOLD")?><span class="symbol required"></span>
													</label>
													<div class="col-sm-2">
														<label class="checkbox-inline">
															<?php echo $form->getElement('hold');?>
														</label>													
													</div>
		</div>
										   
							<label class="control-label col-md-2"><?php echo $tr->translate("IMAGE")?> <span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="form-group last">
									<div class="col-md-12">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
												<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
											</div>
											<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
											</div>
											<div>
												<span class="btn default btn-file">
												<span class="fileinput-new">
												Select image </span>
												<span class="fileinput-exists">
												Change </span>
												<input type="file" name="...">
												</span>
												<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
												Remove </a>
											</div>
										</div>
										<div class="clearfix margin-top-10">
											
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-sm-12" style="padding: 0;">
											<div class="form-group">
												<div class="col-sm-12">
													<div class="tabbable" style="" id="tabShwo">
														<ul id="myTab" class="nav nav-tabs" style="background:#65879A;">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION & ADDRESS")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("SHOW_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example4" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("CUSTOMER_HISTORY")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example5" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("MEMBERSHIP")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
													<div class="tab-content">
														<div class="tab-pane fade in active" id="myTab_example1">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PHONE_2")?> 
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('phone_2');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TITLE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('title');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS_2")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address_2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CITY")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('city');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("COUNTRY")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('country');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX_2")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax_2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>																											
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example2">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example4">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example5">
															<div class="form-group">
																<div class="form-group ">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?><span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														
														<div class="tab-pane fade" id="myTab_example3">
															<div class="form-group">
																<div class="form-group">
																	<div class="col-sm-12">
																		<?php echo $tr->translate("NOTED")?>
																	</div>
																	<div class="col-sm-12">
																		<?php echo $form->getElement('noted');?>
																	</div>
																</div>	
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/customer/credit"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
				 </div>
				</form>
			</div>
		</div>
	</div>
</div>