<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'item','action'=>'index'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'item','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("MENU_GROUP")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="alert alert-danger display-hide">
							<button class="close" data-close="alert"></button>
								You have some form errors. Please check below.
						</div>
						<div class="alert alert-success display-hide">
							<button class="close" data-close="alert"></button>
								Your form validation is successful!
						</div>
						<div class="panel-body">
								<div class="col-sm-9">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("MENU_ITEM_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('item_code');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('description');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("LANG_ONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('lang_1');?>
												</div>
											</div>
											
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
													<label class="col-sm-4 control-label">
														<?php echo $tr->translate("LANG_TWO")?>
													</label>
													<div class="col-sm-8">
														<?php echo $form->getElement('lang_2');?>
													</div>
												</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-12">
													<label class="col-sm-4 control-label">
														<?php echo $tr->translate("PRICE")?> <span class="symbol required"></span>
													</label>
													<div class="col-sm-8">
														<?php echo $form->getElement('demo3');?>
													</div>
												</div>
											</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("DISPLAY_BY")?> 
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('show_description');?>
												</div>
											</div>
											
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group col-sm-6">
												<label class="control-label col-md-4"><?php echo $tr->translate("IMAGE")?> <span class="required">
													 </span>
												</label>
												<div class="col-md-8">
													<div class="form-group last">
														<div class="col-md-12">
															<div class="fileinput fileinput-new" data-provides="fileinput" style="width: 200px; height: 150px;">
																<label id="display_titel" class="full-size" style="border:1px solid #ccc;">
																	<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" style="padding:3px ;background:#7C9BAB none repeat scroll 3px;"/>
																</label>
																<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
																</div>
																<div>
																	<?php echo $form->getElement('photo');?>
																	<a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">
																	Remove </a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-12">
													<div class="tabbable" id="tabShwo" style="">
														<ul id="myTab" class="nav nav-tabs" style="background-color:#65879A;">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("PICTUR_OF_NEMU_ITEM")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
														<div class="tab-content">
															<div class="tab-pane fade in active" id="myTab_example1">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("MENU_GROUP_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('menu_group');?>
																		</div>
																	</div>
																	
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("ROOT_MENU_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('root_menu');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("PRINTER_CODE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('print_code');?>
																		</div>
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="col-sm-2">
																		<?php echo $form->getElement('print_to');?>
																		<?php echo $tr->translate("PRINT_TO_PRINTER")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('active');?>
																		<?php echo $tr->translate("ACTIVE")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('is_service');?>
																		<?php echo $tr->translate("IS_SERVICE")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('show_screen');?>
																		<?php echo $tr->translate("SHOW_SCREEN")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('is_root');?>
																		<?php echo $tr->translate("IS_ROOT")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('time');?>
																		<?php echo $tr->translate("TIME")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('discount');?>
																		<?php echo $tr->translate("DISCOUNT")?>												
																	</div>
																	<div class="col-sm-2">
																		<?php echo $form->getElement('require_qty');?>
																		<?php echo $tr->translate("REQUIRE_QTY")?>												
																	</div>
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("ADDITIONAL_CHARGE")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('demo4');?>
																		</div>
																	</div>
																	<div class="form-group col-sm-6">
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("APPLY_TO_COMPANY")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('select_apply');?>
																		</div>
																	</div>
																</div>
																
															</div>															
														</div>
														<div class="tab-pane fade in " id="myTab_example2">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("BACK_COLOR")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('backgroun_color');?>
																		</div>
																	</div>
																	
																</div>
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-6" >
																		<label class="col-sm-4 control-label" for="form-field-1">
																			<?php echo $tr->translate("FONT_COLOR")?>
																		</label>
																		<div class="col-sm-8">
																			<?php echo $form->getElement('font_color');?>
																		</div>
																	</div>
																	
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FONT_SIZE")?>
																	</label>
																	<div class="col-sm-3">
																		<div id="spinner4">
																			<div class="input-group" >
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-up blue">
																					<i class="fa fa-plus"></i>
																					</button>
																				</div>
																				<?php echo $form->getElement('font_size');?>
																				<div class="spinner-buttons input-group-btn">
																					<button type="button" class="btn spinner-down red">
																					<i class="fa fa-minus"></i>
																					</button>
																				</div>
																			</div>
																		</div>  
																	</div>
																</div>
																
															</div>															
														</div>
														<div class="tab-pane fade in " id="myTab_example3">
															<div class="form-group">
																<div class="col-sm-12" style="padding: 0;">
																	<div class="form-group col-sm-12" >
																		<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("NOTE")?>
																		</label>
																		<div class="col-sm-11">
																			<?php echo $form->getElement('note');?>
																		</div>
																	</div>
																</div>
																
															</div>															
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="btnsave" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit"  name="btnsaveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<a href="<?php echo $this->baseUrl();?>/menu/item/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
							</div>
						</div>
					
				</form>
			</div>
		</div>
	</div>
</div>
<script>
function displayPhoto(){
	
	dis_type=$("#show_description").val();
	bg_color= $("#backgroun_color").val();
	font_color= $("#font_color").val();
	font_size = $("#font_size").val();
	if(dis_type==1){
		dis_title = $("#item_code").val();
	}else if(dis_type==2){
		dis_title = $("#description").val();
	}
	else if(dis_type==3){
		dis_title = $("#lang_1").val();
	}
	else if(dis_type==4){
		dis_title = $("#lang_2").val();
	}
	else{
		dis_title = '';
	}
	$("#display_titel").html(dis_title);
	$("#display_titel").css({"background-color": bg_color,"color": font_color,"font-size":font_size+"px" });
}
</script>