<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
	$url = $this->url(array('module'=>'menu','controller'=>'item','action'=>'add'));
	$url_edit = $this->url(array('module'=>'menu','controller'=>'item','action'=>'edit'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="fa fa-globe"></i>MENU_GROUP				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-bordered table-hover" id="sample_2">
							<thead>
							<tr>
								<th>
							    	id
								</th>
								<th>
									menu_item_code
								</th>
								<th>
									description
								</th>
								<th>
									 lang_one
								</th>
								<th>
									 lang_two
								</th>
								<th>
									show_description
								</th>
								<th>
									price
								</th>
								<th>
									menu_group_code
								</th>
								<th>
									root_menu_code
								</th>
								<th>
									printer_code
								</th>
								<th>
									print_to_printer
								</th>
								<th>
									active
								</th>
								<th>
									show_screen
								</th>
								<th>
									is_root
								</th>
								<th>
									time
								</th>
								<th>
									discount
								</th>
								<th>
									requir_qty
								</th>
							</tr>
							</thead>
							<tbody>
							<tr>
							<?php foreach ($this->rows as $key =>$row){?>
							       <tr class="odd" role="row">
							        <td><?php echo $key+1;?></td>
							        <td><?php echo $row["bar_code"];?></td>
							        <td><?php echo $row["desc"];?></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang1"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["lang2"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["display_by"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["price"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["category_id"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["root_menuid"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["print_code"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["printto_print"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["status"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["showscreen"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["is_root"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["time"];?></a></td>
							         <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["is_discound"];?></a></td>
							        <td><a href="<?php echo $url_edit; ?>/id/<?php echo $row['id'];?>"><?php echo $row["is_reqty"];?></a></td>
							       </tr>
							    <?php }?>
							</tr>
							</tbody>
					</table>
					
				</div>
			
		</div>
	</div>